### ISSUE TITLE
 Exception during run: ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by wz14** [sCrypt-Inc/scrypt-btc-counter#1]
After run `npm run test`, some errors happened. I'm not familiar with the typescript, does I need install some dependency?

npm version 9.8.1

```
> scrypt-btc-counter@0.1.0 test
> npm run test:mocha


> scrypt-btc-counter@0.1.0 test:mocha
> cross-env NETWORK=local mocha


 Exception during run: ReferenceError: crypto is not defined
    at Object.<anonymous> (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/@cmdcode/tapscript/node_modules/@cmdcode/buff-utils/dist/module.mjs:353:29)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/tests/counter.test.ts:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.exports.requireOrImport (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/mocha/lib/nodejs/esm-utils.js:53:16)
    at async Object.exports.loadFilesAsync (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/yufengzhang/Workplace/opcats/scrypt-btc-counter/node_modules/mocha/lib/cli/run.js:370:5)
```

**Comment by wz14** [comment]
solved by updating node to 20
